// Generated by CoffeeScript 1.7.1

/**
  * 截取文章内容
  * @param {string} content 文章的内容
  * @param {boolean} [moreTag] 是否只截取moreTag之前的内容
  * @return {string} 被截取的文章内容
 */

(function() {
  exports.cutContent = function(content, moreTag) {
    var moreTagIndex, ret;
    if (moreTag == null) {
      moreTag = false;
    }
    ret = content;
    if (moreTag === true) {
      moreTagIndex = ret.indexOf('<!--more-->');
      if (moreTagIndex !== -1) {
        ret = ret.substring(0, moreTagIndex);
      }
    }
    return ret;
  };

}).call(this);

//# sourceMappingURL=post.map
